import io
import requests
import pygame
from audioPipeline import process_advisory_audio_by_coordinates

pygame.mixer.init()

# 1. Selected Farm Location on Map (Madurai, Tamil Nadu: 9.8821, 78.0815)
map_lat = 9.8821
map_lon = 78.0815

print(f"1. Fetching live telemetry simulation for coordinates [{map_lat}, {map_lon}]...")

# 2. Query your live FastAPI backend
sim_payload = {
    "engine": "Krishi-Twin-Decision-Core",
    "farm_profile": {
        "coordinates": {"latitude": map_lat, "longitude": map_lon},
        "crop": "Rice (Paddy)",
        "detected_symptom": "Leaf Blight"
    },
    "meteorological_risk": {
        "rain_next_24h_mm": 18.5,
        "rain_probability_pct": 95,
        "computed_washoff_risk": "HIGH"
    },
    "financial_inputs": {
        "spray_cost_inr": 850.0,
        "potential_crop_loss_inr": 4200.0
    }
}

backend_url = "http://localhost:8080/api/v1/simulate"
sim_response = requests.post(backend_url, json=sim_payload)

if sim_response.status_code == 200:
    sim_data = sim_response.json()
    
    # Extract dynamic voice script generated by Gemini 3.6 Flash
    dynamic_advisory = sim_data["voice_script_2_sentences"]
    print(f"\n[Gemini AI Output]: \"{dynamic_advisory}\"")

    # 3. Process dynamic text through regional geofenced audio pipeline
    print("\n2. Synthesizing audio for regional map location...")
    audio_result = process_advisory_audio_by_coordinates(
        raw_text=dynamic_advisory, 
        lat=map_lat, 
        lon=map_lon
    )

    print(f"Mapped Language Code: {audio_result['resolved_language']}")
    print(f"Translated Advisory: {audio_result['translated_text']}")
    print("\n3. Playing dynamic audio...")

    # 4. Stream audio directly through speakers
    audio_stream = io.BytesIO(audio_result['audio_bytes'])
    pygame.mixer.music.load(audio_stream)
    pygame.mixer.music.play()

    while pygame.mixer.music.get_busy():
        pygame.time.Clock().tick(10)

    print("Playback complete!")
else:
    print(f"Error calling simulation backend: {sim_response.status_code} - {sim_response.text}")